---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Constant-FromGlobal
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Data::OptList: 0
  Test::More: 0.88
  constant: 0
  perl: 5.008
  warnings: 0
resources:
  repository: https://github.com/neilbowers/constant-fromglobal
version: 0.04
