---
abstract: 'declare constant(s) with value from global or environment variable'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Constant-FromGlobal
requires:
  Carp: 0
  Data::OptList: 0
  Scalar::Util: 0
  constant: 0
  perl: v5.8.0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/neilbowers/constant-fromglobal
  repository: https://github.com/neilbowers/constant-fromglobal.git
version: 0.05
