---
abstract: 'declare constant(s) with value from global or environment variable'
author:
  - 'Neil Bowers <neilb@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Constant-FromGlobal
requires:
  Carp: '0'
  Data::OptList: '0'
  Scalar::Util: '0'
  constant: '0'
  perl: v5.8.0
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Constant-FromGlobal
  repository: https://github.com/neilbowers/Constant-FromGlobal.git
version: '0.07'
